name: Deploy to GitHub Pages
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/bootstrap
      - run: npm run build
      - name: Setup git config
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
      - name: Commit
        run: |
          git add -f www
          git commit -m "Build for deploy"
      - run: |
          git subtree split --prefix www -b gh-pages
          git push -f origin gh-pages:gh-pages
